### ISSUE TITLE
网站监控--修改的时候字段缺少校验

### ISSUE THREAD

**Issue by enica** [enica/-#4]
修改的时候字段缺少校验
![5a17verl6o 3 tmt hovgj](https://cloud.githubusercontent.com/assets/6247206/26298245/23e17fa4-3f09-11e7-83b1-cf8158fafeda.png)

**Comment by enica** [comment]
名称长度为做限制例如：12345678901234567890123456789012345678901234567890123456789012345678901234567890

**Comment by animelfc** [comment]
已加检验
